### ISSUE TITLE
Mac os intel chips

### ISSUE THREAD

**Issue by MohmmadSawalha-ios** [Razviar/marvelsnaptracker#24]
are going to have a support version for mac os with intel chips ? :(

**Comment by MohmmadSawalha-ios** [comment]
@Razviar

**Comment by hadamlenz** [comment]
bump +1

**Comment by Razviar** [comment]
Sorry, we don't have mac supporter/maintainer in our team. Basically I don't even have a mac computer to dev something for mac lol. If there's anyone how wants to step in and add mac support - it will be appreciated. 

Since the project is Electron, it's cross-platform and in theory should be working on mac too.

**Comment by hadamlenz** [comment]
I gave building a try on Apple Silicon.  The app gets built, but I get the following error.  Ill dig a little more after work.  my first electron app

```
marvelsnaptracker adamlenz$ electron-builder --arm64
  • electron-builder  version=23.6.0 os=22.3.0
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=macos-alias@0.2.11 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=22.2.0 appOutDir=dist/mac-arm64
  • default Electron icon is used  reason=application icon is not set
  ⨯ Application entry file ".webpack/main" in the "/Users/adamlenz/Sites/marvelsnaptracker/dist/mac-arm64/Marvel Snap Tracker.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file ".webpack/main" in the "/Users/adamlenz/Sites/marvelsnaptracker/dist/mac-arm64/Marvel Snap Tracker.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at MacPackager.checkFileInPackage (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
    at MacPackager.sanityCheckPackage (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
    at MacPackager.doPack (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at MacPackager.pack (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:192:7)
    at Packager.doBuild (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/opt/homebrew/lib/node_modules/electron-builder/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/opt/homebrew/lib/node_modules/electron-builder/node_modules/builder-util/src/promise.ts:12:14)
 ```

**Comment by Razviar** [comment]
@hadamlenz looks like it's something with electron forge config. Please take a look at our another repo: https://github.com/Razviar/mtgap

For that tracker we had mac maintainer, but at this moment he is not taking an active part in development. But you might find some insights there

**Comment by MohmmadSawalha-ios** [comment]
I can help i have mac with intel chip, heads-up this would be my first attempt i am a mobile engineer

**Comment by MohmmadSawalha-ios** [comment]
@hadamlenz ill be available in 2 hours you can ping me on discord i would love to help Tobi#0830

**Comment by Razviar** [comment]
If you guys will make a chat please add me there too Razviar#0930

I might help with getting up to speed with electron

**Comment by MohmmadSawalha-ios** [comment]
Thanks @Razviar  will do

**Comment by Razviar** [comment]
We also have flutter mobile tracker https://github.com/Razviar/snap_tracker_app

People are asking if it could work for iOS too lol

**Comment by MohmmadSawalha-ios** [comment]
> We also have flutter mobile tracker https://github.com/Razviar/snap_tracker_app
> 
> People are asking if it could work for iOS too lol

I am familiar with flutter mainly i work with swift natively but i have done few projects on flutter will take a look, we can talk about it on discord

**Comment by konjelly** [comment]
I don't have any experience with electron, but if you need any help testing on ARM Macs I'd love to help.
