### ISSUE TITLE
Marvel App Tracker not Syncing...

### ISSUE THREAD

**Issue by HarIeeQueen** [Razviar/marvelsnaptracker#57]
Hello,

I have had download and installed the last app version and tried couple times and nothing. Then wiped all settings and tried again. More than a few times and still nothing. After those tries, I restarted the laptop and still nothing. It recognizes that I've a SNAP acct and the MSNAPPro acct. Everything opens smoothly, no problem. But when I click Sync it opens a window greeting me and sort and once I confirm things...NOTHING...It just stays there...can you guys please help??? 

Thanks so much in advance!

**Comment by Razviar** [comment]
Hello!

It's not possible to understand what exactly is happening on your side according to this description. Please provide more details:

1. Are you registered on marvelsnap.pro and are you logged in?
2. Screenshots or video of your screen with sync attempt
3. Some credentials which would help us identify your account: snap nick, partial email (part before @)

**Comment by HarIeeQueen** [comment]
Thank you so much for your response. I’ve had gathered some screenshots for you to help trying to solve the problem.

In this one you can see I’m logged in…
![1](https://github.com/Razviar/marvelsnaptracker/assets/145724511/a7185a33-9a5c-4d89-8b6e-f09c7da6af71)

Here besides of seeing my Snap Nick you can see I’m about to Sync Account…
![2](https://github.com/Razviar/marvelsnaptracker/assets/145724511/4a460f2a-cee2-4347-9045-d947e276ce56)

After verifying both options are correct, I proceed to confirm…
![3](https://github.com/Razviar/marvelsnaptracker/assets/145724511/e7f9bdf9-a67f-4754-9ef7-449c61c2f9d9)

As you can see is “Linking” but that’s as far as it goes…it never links…it just stays like that!
![4](https://github.com/Razviar/marvelsnaptracker/assets/145724511/4c4a54e1-8851-40fd-91d3-290da664aa9b)

I truly appreciated all your help. Thanks so much in advance once again 🙏🏼😊
Sincerely,
HarleeQueen

**Comment by HarIeeQueen** [comment]
You're very welcome...this is what shows as a failed to load or with blocked a frame

Failed to load resource: the server responded with a status of 400 ()
2adthrive.min.js?deployment=2023-09-22-1:0a6bab1:con&bucket=flex-01&deliveryFeatures=rubiconFloors,recencyFrequency,ttdSync,reissuingSticky,manualCookieSync,raptiveFloors&siteid=6388b71c8816820994db3176:50 LiveRampAtsTrackerComponent::_setECSTags eCST set succesfully
4VM121 teads-vpaid-display.js:1 Uncaught DOMException: Blocked a frame with origin "https://marvelsnap.pro" from accessing a cross-origin frame.
    at f._log (https://a.teads.tv/media/vpaid-display/teads-vpaid-display.js:1:20517)
    at f.info (https://a.teads.tv/media/vpaid-display/teads-vpaid-display.js:1:20182)
    at https://a.teads.tv/media/vpaid-display/teads-vpaid-display.js:1:29342

**Comment by HarIeeQueen** [comment]
I don't understand it very well but it looks like something is blocking the last step. I installed updates that were ready and restart the laptop and after I attempted the syncing again, this was what shows:

2adthrive.min.js?deployment=stable&bucket=prod&deliveryFeatures=rubiconFloors,recencyFrequency,ttdSync,reissuingSticky,manualCookieSync,raptiveFloors&siteid=6388b71c8816820994db3176:50 LiveRampAtsTrackerComponent::_setECSTags eCST set succesfully
/snap/do.php?cmd=dosync:1 
        
        
        Failed to load resource: the server responded with a status of 502 ()
j
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://c1.adform.net/serving/cookie/match?party=1301&gdpr=[GDPR]&gdpr_consent=[GDPR_CONSENT].
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://c1.adform.net/serving/cookie/match?party=1301&gdpr=[GDPR]&gdpr_consent=[GDPR_CONSENT].
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://c1.adform.net/serving/cookie/match?CC=1&party=1301&gdpr=[GDPR]&gdpr_consent=[GDPR_CONSENT].
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://token.rubiconproject.com/khaos.json?.
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://token.rubiconproject.com/khaos.json?.
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://token.rubiconproject.com/khaos.json?.
marvelsnap.pro/:1  Tracking Prevention blocked access to storage for https://c1.adform.net/serving/cookie/match?CC=1&party=1301&gdpr=[GDPR]&gdpr_consent=[GDPR_CONSENT].

Hopefully, this might be of help ;) !!!

**Comment by Razviar** [comment]
Must be AdBlock. If you are using it, please disable and try again

**Comment by HarIeeQueen** [comment]
I've turned off the Tracking Prevention from Microsoft Edge. Even tried to copy and paste the link to Chrome and still nothing :(

**Comment by HarIeeQueen** [comment]
Oh my...the joy of making this work...I ended up trying the whole process with Maxthon Web Browser and it worked as it gave me the "Perfect! All Set Now" message...Thank you so so much for all your help ;) Have a lovely weekend!
